lsi: false
safe: true
source: /docs
incremental: false
highlighter: rouge
remote_theme: pages-themes/merlot@v0.2.0
plugins:
- jekyll-remote-theme
title: The company docs
description: the company docs placeholder, please follow the contribution guidelines
gist:
  noscript: false
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge